version: '3.8'

services:
  thanatos-bot:
    build: .
    container_name: thanatos-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - PYTHONUNBUFFERED=1
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/thanatos.db').close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
